### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [sarteleb/tc359-project3#1]
Same comment as in previous project regarding valid HTML:

> This isn't completely valid HTML unfortunately. Try making sure your HTML files don't return any errors (warnings are OK) when uploaded to [the W3C Validator](http://validator.w3.org/), then let me know when the repo is updated.

**Comment by sarteleb** [comment]
Fixed.

**Comment by chrisvfritz** [comment]
Same problem unfortunately. Still seeing HTML errors for [your Heroku app](https://tc359-project1-sarteleb.herokuapp.com/).
